apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    app: "message-wall-front"
    name: "message-wall-front-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/hsavolai/test-ocp-dbtesting.git"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipeline/Jenkinsfile
kind: List
metadata: []
